### ISSUE TITLE
Slow internet not showing loading icon when changing lesson

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#364]
## This issue causes bouncing from the website

The internet speed mentioned exists in some Arab countries

## Reproduce Steps

1. Use Private Browsing

From Web Dev Tools => Network Tab

2. Create Slow Internet

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/c5365f52-fcd0-4bd1-a128-d3cf1d0e3c1f)

3. Choose Slow Internet

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/c99baa23-e65b-431f-90bc-f631b09a4aee)

4. Whenever you change a lesson no loading icon shows to let the user know that it's loading

**Comment by yaseralnajjar** [comment]
I'm reopening this as the problem still exists in different form

* This happens when changing the lesson (video to video)

Please check this video:

https://drive.google.com/file/d/13CRm2HIZ3V90JWHwEcCI86VE2eDSKGDi/view?usp=sharing

**Comment by LouayH** [comment]
Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/93f552863b5683cbb090971fc1d59d0924e01477)
