### ISSUE TITLE
Live chat shows ugly in phones

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#375]
![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/ac318ad1-167a-40aa-b1c2-be6b7cc50508)

**Comment by LouayH** [comment]
Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/d8c01df828a86ecf187329e8823c4fa45181b61d)
