### ISSUE TITLE
Profile settings page side menu not covering the whole page

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#378]
Current behavior:

When you profile settings in the link: https://spa-dev.coretabs.net/profile/profile-info

It will show as

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/7c72a33d-652b-4390-9078-2ecb7b17d0f8)

**Comment by LouayH** [comment]
Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/c33fa7dadb3b8cc418d4c3bbc53a8fbcb3057cdb)
