### ISSUE TITLE
show community link for non-registered people

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#379]
Current behavior:

When an anonymous user shows a profile, he will see the following

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/db3d649d-b32b-40d4-9a37-46018f3dcf71)

Desired:

Add link for "community"

**Comment by LouayH** [comment]
Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/2c6ad250a185a4f426f3d79a8c374914f727ad51)
