### ISSUE TITLE
live support not displaying inside classroom

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#380]
Current behavior:

Users might face issues inside the classroom, but the live support is hidden

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/6a91fe94-b054-4d31-9bfb-a5877505d197)

**Comment by LouayH** [comment]
There is no place for it in the inner pages after we add Navigation Drawer, I’ve tried it on the left side but it doesn’t support change location.

Users may face some issues there but still can go back to homepage and start a live chat, or click on one of those Coretabs Community buttons to ask for assistance.

**Comment by yaseralnajjar** [comment]
I didn't comment till now to try to realize the use cases of keeping the support in the classroom.

The use cases I saw are:

1. Someone who reached the support (from the homepage or login) might not be able to continue the conservation after he gets into the classroom.

2. Students reach the support even when they have a question about the academy (in general, not necessarily an issue), and having the direct contact is more convenient for them... we have taken about 25% of the conversations from the classroom.

Mohammed @Alhakem has an idea on how to style this...

**Comment by Alhakem** [comment]
# first problem:
Drift Widget Icon is over the navigator drawer.
![image.png](https://images.zenhubusercontent.com/5b3a8c2eaf2e4e3c8d3cb8b9/780c35ff-b8b7-49cd-90b4-b534f50f6a66)
**I suggest** to give it a margin form right side to overcome this problem

# Second problem:
whenever  the navigator drawer is toggled, the Icon still appears on top of it
![image.png](https://images.zenhubusercontent.com/5b3a8c2eaf2e4e3c8d3cb8b9/4dd42451-8b33-4c01-b350-f49c7f33fdd7)
**I suggest** once the navigator drawer is opened (mini = false) we hide `#drift-widget`

However we gonna need to get rid of the icon in small screens the way Louay did, and I don't mind that as long as we have it in desktops

**Comment by LouayH** [comment]
I applied it, pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/7ffd0ed078e42f92c114d07ef18044ff85d8222c)

Please take a look

**Comment by Alhakem** [comment]
Looks Great!
