### ISSUE TITLE
Keeping the profile country empty doesn't allow submitting

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#387]
You can clear up your country field from the django admin

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/c282c1ad-0217-446c-8e31-bcdd174b9bd9)

**Comment by LouayH** [comment]
Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/2c5b15c84e4491001c858d17ff7faf6238579f03)

**Comment by yaseralnajjar** [comment]
I'm reopening this as we the endpoint can now accept PATCH requests without specifying the country

**Comment by LouayH** [comment]
Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/e9b763248dba655d379034c158d3478d36b77f82)
