### ISSUE TITLE
username changing should not accept arabic

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#395]
Since this affects discourse

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/96cf8175-1763-461a-81ec-b2c94838c150)

**Comment by LouayH** [comment]
Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/cf7ce734535252f3109d8a99530abdead692fac8)
