### ISSUE TITLE
login menu not working in small screens (half desktop)

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#403]
![Untitled.jpg](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/99c300c0-c815-4dd9-95b6-3b24410c766d)

**Comment by yaseralnajjar** [comment]
Possible replicate of https://github.com/Alhakem/coretabs-academy/issues/406

**Comment by LouayH** [comment]
Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/f6546c60f7aad3aca0b6f135bbc9cdf9bfa13a12)
