### ISSUE TITLE
Invalid scroll bar appears in Firefox

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#404]
![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/39268110-d8cf-482b-8d5f-623d999e7d46)

**Comment by LouayH** [comment]
Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/33231186c88514539b583a567ffd74319af9b26e)
