### ISSUE TITLE
Tracks page show lots of white space on Samsung Tab 8

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#405]
To view the issue: http://quirktools.com/screenfly/#u=https%3A//coretabs.net/tracks/backend&w=1440&h=2960&s=1

* You can reproduce the issue using browser dev tools (ctrl shift i) too.

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/4c3f9b71-85e0-48e9-9f08-678354967d70)

**Comment by LouayH** [comment]
Did you face this problem really on Samsung Tab 8, or it just an emulation on Screenfly?

**Comment by yaseralnajjar** [comment]
We've got a report from a user having this problem on his Tab

**Comment by LouayH** [comment]
Did he send any screenshots?

**Comment by yaseralnajjar** [comment]
I checked the reported issue, the user said on Note 9 (not Tab 8).

I found a Note 9 to try it out myself, and the page is perfectly fine, so I'm closing this 👍
