### ISSUE TITLE
Menu not working on iPad

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#406]
Menu is disabled on the ipad

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/00beabb0-78b1-459f-8dff-48c115e81d2d)

**Comment by LouayH** [comment]
Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/f6546c60f7aad3aca0b6f135bbc9cdf9bfa13a12)
