### ISSUE TITLE
counter shows zero in tracks page

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#407]
It's better if we switch the implementation instead of fixed date to a timedelta one like:

```
Date.prototype.addDays = function(days) {
    var date = new Date(this.valueOf());
    date.setDate(date.getDate() + days);
    return date;
}

var date = new Date();

alert(date.addDays(5));
```

More info: https://stackoverflow.com/questions/563406/add-days-to-javascript-date

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/1236913c-a4d3-493b-9206-2ed691287a60)

**Comment by LouayH** [comment]
I don't understand why should we change the implementation, as long it's working well with current one.

We just need to set the deadline, and if you want, we can make it settable from back-end, just provide us with endpoint URL that returns deadline in similar formula "june 21, 2019".

**Comment by yaseralnajjar** [comment]
This would help us in the meantime to not update the date every time manually

If the technical implementation is not worth it, then let's keep it as it and change the date manually 👍

**Comment by LouayH** [comment]
Any solution that can do the trick automatically worth to be implemented.

But I didn't get it, how the suggested implementation can help us?

**Comment by yaseralnajjar** [comment]
It would be setting the timer 3 days ahead everytime the user opens that page

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LouayH** [comment]
So we don't have a certain deadline, and countdown will always launch at 3 days!

I don't think this is good practice, we should have a certain deadline.

**Comment by LouayH** [comment]
Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/0cbb6e35784017227536ebe220613a9c1c623868)
