### ISSUE TITLE
Track page malformed in landscape Pixel2

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#408]
Reproducing the bug:

1. Open dev tools (ctrl shift i)
2. Choose mobile mode and pick Pixel2 device
3. Change orientation into landscape (as shown in the pic below)

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/054f84e3-e06e7-476d-92d3-5d9d9ccd2861)

**Comment by LouayH** [comment]
If it's not done by this commit, then fix image's URL please.

Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/c045a0c33b9de1034c25becc96cddb173580aa96)
