### ISSUE TITLE
Prices part is malformed in iPad

### ISSUE THREAD

**Issue by yaseralnajjar** [Alhakem/coretabs-academy#409]
## Landscape

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/08e78c27-dee3-4ab6-b49e-6cccfc41b618)

## Portrait (not showing "شاملة")

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/dbf03d18-ccfa-4aa6-b295-2728c0af0a5f)

**Comment by LouayH** [comment]
Pushed to [develop](https://github.com/Alhakem/coretabs-academy/commit/7916db82351aefc1b0ae642439a4943f5e762c8a)
